### ISSUE TITLE
README correction and Undefined 'WPRINT_BT_APP_INFO'

### ISSUE THREAD

**Issue by prapkengr** [LairdCP/ewb_wiced_demo#2]
1.
Please correct the README.

Wrong statement.
_3. Copy the two .h files and one .a file from 
    ...\algo\bin\Normal_version\gcc\Cortex_M4F_

Corrected:
_3. Copy the two .h files and one .a file from 
    ...\algo\normal_version\bin\gcc\Cortex_M4_

Because, gcc/Cortex_M4F is with `-mfpu=fpv4-sp-d16 -mfloat-abi=hard` which is not the case with \WICED-Studio-6.4\

2.
For the error

`Undefined 'WPRINT_BT_APP_INFO'`

Add the following lines in the _apps\laird\demo\ble\profiles\wifi_config_profile.h_

```
/* Bluetooth application tracing macro */
#ifndef WPRINT_BT_APP_INFO
extern wiced_mutex_t global_trace_mutex;
#define WPRINT_BT_APP_INFO(info)    { \
                                        wiced_rtos_lock_mutex(&global_trace_mutex);     \
                                        WPRINT_APP_INFO(info);                          \
                                        wiced_rtos_unlock_mutex(&global_trace_mutex);   \
                                    }
#endif

```

**Comment by randyscott** [comment]
Fixed by f099f8c1e500f0489d835fd8467e67b6fe59e046
